version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: pulse-check-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pulsecheckdb
    ports:
      - "3307:3306"