spring.application.name=pulsecheck

# MySQL config
spring.datasource.url=jdbc:mysql://localhost:3307/pulsecheckdb
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Email
spring.mail.host=smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=713bdc8738cde5
spring.mail.password=bdbcb8db45433f
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.sendgrid.api.key=YOUR_API_KEY